apiVersion: v1
kind: Service
metadata:
  name: baseline-board
  namespace: zone-current-env
  labels:
    app: baseline-board
spec:
  type: NodePort
  ports:
    - name: tcp-20151
      protocol: TCP
      port: 20151 # 集群端口
      targetPort: 20151 # pod内容器端口
  selector:
    app: baseline-board
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-board
  namespace: zone-current-env
  labels:
    app: baseline-board
    version: v1
spec:
  replicas: replicas-num
  selector:
    matchLabels:
      app: baseline-board
  template:
    metadata:
      labels:
        app: baseline-board
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
#        - name: board-pvc
#          persistentVolumeClaim:
#            claimName: baseline-board
      containers:
        - name: baseline-board
          image: 10.163.205.239:8081/baseline-current-env/baseline-boardtag-name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20151
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
#            - name: board-pvc
#              mountPath: /home/baseline/board/attendance
#            - name: board-pvc
#              mountPath: /home/baseline/board/requirement
