apiVersion: v1
kind: Service
metadata:
  name: baseline-ghost
  namespace: zone-current-env
  labels:
    app: baseline-ghost
spec:
  type: NodePort
  ports:
    - name: tcp-20181
      protocol: TCP
      port: 20181 # 集群端口
      targetPort: 20181 # pod内容器端口
  selector:
    app: baseline-ghost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-ghost
  namespace: zone-current-env
  labels:
    app: baseline-ghost
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseline-ghost
  template:
    metadata:
      labels:
        app: baseline-ghost
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: baseline-ghost
          image: 10.163.205.239:8081/baseline-current-env/baseline-ghosttag-name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20181
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime

