apiVersion: v1
kind: Service
metadata:
  name: baseline-demand
  namespace: zone-current-env
  labels:
    app: baseline-demand
spec:
  type: NodePort
  ports:
    - name: tcp-20211
      protocol: TCP
      port: 20211 # 集群端口
      targetPort: 20211 # pod内容器端口
  selector:
    app: baseline-demand
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-demand
  namespace: zone-current-env
  labels:
    app: baseline-demand
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseline-demand
  template:
    metadata:
      labels:
        app: baseline-demand
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: baseline-demand
          image: 10.163.205.239:8081/baseline-current-env/baseline-demandtag-name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20211
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
